/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U32[17]/U34[4]/J10[20] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SCL_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U32[18]/U34[6]/J10[18] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SDA_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_EMC_B2_04 (coord M1), SEMC_D20/U25[8] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D20_PERIPHERAL                                  SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D20_SIGNAL                                  sai_mclk   /*!< Signal name */

/* GPIO_EMC_B2_08 (coord P1), SEMC_DM2/U25[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM2_PERIPHERAL                                  SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM2_SIGNAL                               sai_tx_data   /*!< Signal name */

/* GPIO_EMC_B2_10 (coord R2), SEMC_D25/U25[44] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D25_PERIPHERAL                                  SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D25_SIGNAL                               sai_tx_sync   /*!< Signal name */

/* GPIO_EMC_B2_09 (coord N2), SEMC_D24/U25[42] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D24_PERIPHERAL                                  SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D24_SIGNAL                               sai_tx_bclk   /*!< Signal name */

/* GPIO_LPSR_09 (coord P5), DMIC_DATA0/U41[5]/J50[20]/LPSPI6_CS0/J26[11] */
/* Routed pin properties */
#define BOARD_INITPINS_DMIC_DATA0_PERIPHERAL                                 MIC   /*!< Peripheral name */
#define BOARD_INITPINS_DMIC_DATA0_SIGNAL                           mic_bitstream   /*!< Signal name */
#define BOARD_INITPINS_DMIC_DATA0_CHANNEL                                     0U   /*!< Signal channel */

/* GPIO_LPSR_08 (coord U8), DMIC_CLK/U41[1]/U44[1]/J50[18] */
/* Routed pin properties */
#define BOARD_INITPINS_DMIC_CLK_PERIPHERAL                                   MIC   /*!< Peripheral name */
#define BOARD_INITPINS_DMIC_CLK_SIGNAL                                       CLK   /*!< Signal name */

/* GPIO_EMC_B2_18 (coord N3), USER_GREEN */
/* Routed pin properties */
#define BOARD_INITPINS_USER_GREEN_PERIPHERAL                               GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_USER_GREEN_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_GREEN_CHANNEL                                    28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_GREEN_GPIO                                     GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_GREEN_GPIO_PIN                                   28U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_GREEN_GPIO_PIN_MASK                      (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_AD_08 (coord R15), USER_RED */
/* Routed pin properties */
#define BOARD_INITPINS_USER_RED_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_USER_RED_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_RED_CHANNEL                                       7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_RED_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_RED_GPIO_PIN                                      7U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_RED_GPIO_PIN_MASK                         (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_AD_10 (coord R17), USER_BLUE */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BLUE_PERIPHERAL                                GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BLUE_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BLUE_CHANNEL                                      9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BLUE_GPIO                                      GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BLUE_GPIO_PIN                                     9U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BLUE_GPIO_PIN_MASK                        (1U << 9U)   /*!< GPIO pin mask */

/* WAKEUP (coord T8), USER_BUTTON */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BUTTON_PERIPHERAL                             GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BUTTON_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BUTTON_CHANNEL                                    0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BUTTON_GPIO                                   GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN                                   0U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN_MASK                      (1U << 0U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
